### ISSUE TITLE
error: invalid output constraint '=a' in asm

### ISSUE THREAD

**Issue by dos1** [mmig/libflac.js#10]
Tried to build from source, but it fails with:

```
  CC       float.lo
cpu.c:91:43: error: invalid output constraint '=a' in asm
        asm volatile (".byte 0x0f, 0x01, 0xd0" : "=a"(lo), "=d"(hi) : "c" (0));
                                                 ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```

**Comment by dos1** [comment]
Seems to be fixed by passing `--host=asmjs` to `configure`

**Comment by russaa** [comment]
yes, I have to admit that since the last update of `emscripten` I did only compile on Windows, so the `make` script may not be up-to-date/working right now

I'll have a look and update the script
