### ISSUE TITLE
Noise while recording on windows

### ISSUE THREAD

**Issue by carbonrider** [mmig/libflac.js#16]
We tried this library on MacAir and the voice was recorded without any significant noise. But we are seeing a strange issue on Windows Laptop (Windows 10, Chrome 78). There is too much of noise getting recorded and also the audio is not audible.

Same results are happening with Demo page as well.

**Comment by russaa** [comment]
Could this be an general issue with the microphone/recording an that device, or is it specific to this encoding library?

Did you try recording to directly to WAV (from within the browser)?
Does it have the same problems?

**Comment by carbonrider** [comment]
Apologies. After going through sound settings, I realised that there was problem with Microphone settings. 😔
