### ISSUE TITLE
Compatibility with Create-React-App / Webpack

### ISSUE THREAD

**Issue by breznik** [mmig/libflac.js#4]
Hi,

I'm pretty new to js/react/webpack. I can import libflac in NodeJS, and nodejs seems happy. When I try to import libflac (minified or non-minified version) to a create-react-app project, I get an error like below:

```
Error in ./src/lib/libflac3-1.3.2.js
Syntax error: Invalid number (2557:18)

  2555 |         return PATH.join.apply(null, parts);
  2556 |       },flagsToPermissionStringMap:{0:"r",1:"r+",2:"r+",64:"r",65:"r+",66:"r+",129:"rx+",193:"rx+",514:"w+",577:"w",578:"w+",705:"wx",706:"wx+",1024:"a",1025:"a",1026:"a+",1089:"a",1090:"a+",1153:"ax",1154:"ax+",1217:"ax",1218:"ax+",4096:"rs",4098:"rs+"},flagsToPermissionString:function (flags) {
> 2557 |         flags &= ~0100000 /*O_LARGEFILE*/; // Ignore this flag from musl, otherwise node.js fails to open the file.
       |                   ^
  2558 |         if (flags in NODEFS.flagsToPermissionStringMap) {
  2559 |           return NODEFS.flagsToPermissionStringMap[flags];
  2560 |         } else {
```

Any suggestions for how to work around this? Not sure if the issue is with the code generated by emscripten or the way create-react-app configures their webpack loader or something else entirely.

**Comment by russaa** [comment]
it could be, that webpack does not like the octal format for numbers, since it is only a "quasi-standard":  
it's not in the spec, but all browsers (and node) support it.

Since ECMAScript 2015 there is a new way for expressing octal numbers, by prefixing them with `0o` (zero + small letter o) instead of just `0` (zero).  

You could try editing the source (i.e. inserting a small o after the leading zero in the number in line 2557) and see, if that works:

```javascript
...
  flags &= ~0o100000 /*O_LARGEFILE*/; // Ignore this flag from musl, otherwise node.js fails to open the file.
...
```

**Comment by breznik** [comment]
Thanks, the 0o octal prefix fixed a couple issues only to expose that webpack is not happy with the module format (warning  'Module' was used before it was defined`). Might have to defer investigating how to workaround that in webpack till another time though.

**Comment by russaa** [comment]
Did you use the minified version of the library?  
It loads asynchronously which may explain the warning about the premature use of the Module.

If you could provide a self-contained example, that demonstrates the problem(s), I'd try looking into it.

**Comment by nickvisut** [comment]
Seems this octal problem is happening with native ES imports as well, which use modules requiring strict mode. This is the error I'm getting in the browser:
![screen shot 2018-07-11 at 5 17 01 pm](https://user-images.githubusercontent.com/2823112/42605693-49851ae2-852e-11e8-8290-72a88983d43a.png)

**Comment by russaa** [comment]
I checked `Emscripten` (the compiler):  
they [addressed the octal-notation problem](https://github.com/kripken/emscripten/commit/0a7ef6f4b01167a71b67abbd052b8cd3f4952a54) in the newer versions.

So, I will compile a new version for `flaclib.js` using the new Emscripten SDK.

But they have some breaking changes, so it will take me some time to migrate to the new compiler version, probably a few days or so.

**Comment by nickvisut** [comment]
Thanks for investigating, and the work and forthcoming fix is much appreciated!

**Comment by russaa** [comment]
It should work now in `strict mode`.  

There is also an additional (more efficient & smaller) version for WebAssembly (`wasm`) that is supported by most of the major browsers by now:  
see the README and the example pages  for more details.

**Comment by nickvisut** [comment]
Thanks, this is great--will give it a go!

As an aside, had you considered publishing your work as an NPM package?

**Comment by russaa** [comment]
not yet via npmjs.com, but thanks to the initiative of @ztl8702 `libflac.js` can now be installed via

    npm install git+https://github.com/mmig/libflac.js.git
