### ISSUE TITLE
Uncaught Error: Cannot find module './utils/data-utils'

### ISSUE THREAD

**Issue by adam-drewery** [mmig/libflac.js#45]
Hi,

I'm trying to use this library with npm and webpack. I have libflacjs v5.4.0 installed.

The application builds correctly, however, when running the Encoder sample in the documentation, the above error occurs. It seems that `encoder.js` is trying to find a module that isn't in the package. Is this a bug or am I doing something silly?

**Comment by russaa** [comment]
In an ideal world that should have worked ;-(
I am guessing, there is some problem with `webpack` being unable to detect dependencies during the built

Could you share the build configuration that you are using for `webpack`?

And how you are requireing / importing `encoder.js`?


_as a quick-fix, you could try using the TypeScript sources from `libflacjs/src/**`, instead of the compiled UMD JavaScript modules in `libflacjs/lib/**`_
_(you would need to configure `webpack` so that it can compile TypeScript)_

**Comment by adam-drewery** [comment]
Hi, thanks for the prompt reply. :) I have been pulling my hair out with this one a bit! Yes, it certainly seems like a webpack related issue to me.

My webpack config is very small (this is a blazor wasm app so `wwwroot` is the site root):

```js
const path = require('path');

module.exports = {
    entry: './scripts/index.js',
    output: {
        filename: 'index.bundle.js',
        path: path.resolve("wwwroot", 'dist')
    }
};
```

I'm importing `Encoder` in my `index.js` with an `import` statement here:

```js
import * as Flac from 'libflacjs/dist/libflac';
import {Encoder} from "libflacjs/lib/encoder";
import {exportFlacFile} from "libflacjs/lib/utils";

window.encodeFlac = (binData) => {
    
    const data = new Int32Array(binData);

    const encodingMode = 'interleaved';// "interleaved" | "channels"
    const sampleRate = 44100;//<- someSampleRate: number, e.g. 44100
    const channels = 2;//<- someChannels: number, e.g. 1 (mono), 2 (stereo), ...
    const bitsPerSample = 16;//<- someBitsPerSample: number, e.g. 8 or 16 or 24
    const compressionLevel = 8;//<- someCompressionLevel: number, value between [0, 8] from low to high compression
    const encoder = new Encoder(Flac, {
        sampleRate: sampleRate, // number, e.g. 44100
        channels: channels, // number, e.g. 1 (mono), 2 (stereo), ...
        bitsPerSample: bitsPerSample, // number, e.g. 8 or 16 or 24
        compression: compressionLevel, // number, value between [0, 8] from low to high compression
        verify: true, // boolean (OPTIONAL)
        isOgg: false // boolean (OPTIONAL), if encoded FLAC should be wrapped in OGG container
    });

    if (encodingMode === 'interleaved') {
        encoder.encode(data);
    }
    encoder.encode();
    const encData = encoder.getSamples();
    const metadata = encoder.metadata;

    encoder.destroy();
    const flacBlob = exportFlacFile([encData], metadata, /* if encode in OGG container: */ false);
    return flacBlob.stream();
}
```

I'll try the TypeScript approach like you suggest and see how it goes.

**Comment by adam-drewery** [comment]
the typescript workaround seems to work!

In addition to setting up typescript compilation, I had to put this in my webpack config:

```js
rules: [
            {
                test: /\.ts?$/,
                loader: 'ts-loader',
                options: { allowTsInNodeModules: true }
                // exclude: /node_modules/,
            },
        ],
```
