### ISSUE TITLE
Importing to react

### ISSUE THREAD

**Issue by jay-shah** [mmig/libflac.js#9]
I'm trying to import libflac in reactjs with 

`var Flac = require('./lib/libflac4-1.3.2.js');`

and i'm getting a tone of errors:

```
Failed to compile.

./src/lib/libflac.js
  Line 24:    'define' is not defined           no-undef
  Line 26:    'define' is not defined           no-undef
  Line 57:    Unexpected use of 'self'          no-restricted-globals
  Line 57:    Unexpected use of 'self'          no-restricted-globals
  Line 218:   'read' is not defined             no-undef
  Line 229:   'readbuffer' is not defined       no-undef
  Line 231:   'read' is not defined             no-undef
  Line 237:   'scriptArgs' is not defined       no-undef
  Line 244:   'quit' is not defined             no-undef
  Line 315:   Unexpected use of 'print'         no-restricted-globals
  Line 315:   Unexpected use of 'print'         no-restricted-globals
  Line 316:   'printErr' is not defined         no-undef
  Line 601:   'tempI64' is not defined          no-undef
  Line 601:   'tempDouble' is not defined       no-undef
  Line 601:   'tempDouble' is not defined       no-undef
  Line 601:   'tempDouble' is not defined       no-undef
  Line 601:   'tempDouble' is not defined       no-undef
  Line 601:   'tempDouble' is not defined       no-undef
  Line 601:   'tempDouble' is not defined       no-undef
  Line 601:   'tempI64' is not defined          no-undef
  Line 601:   'tempI64' is not defined          no-undef
  Line 1815:  'readline' is not defined         no-undef
  Line 2712:  'FileReaderSync' is not defined   no-undef
  Line 3827:  'path' is not defined             no-undef
  Line 4407:  'Browser' is not defined          no-undef
  Line 4436:  'Browser' is not defined          no-undef
  Line 4646:  'SOCKFS' is not defined           no-undef
  Line 4652:  '__read_sockaddr' is not defined  no-undef
  Line 4654:  'DNS' is not defined              no-undef

Search for the keywords to learn more about each error.
```

Any ideas on what I am doing wrong here?

Cheers

**Comment by jay-shah** [comment]
Okay, I figured out what to do, in case anybody else has the same issue this is how I solved it...

install via npm:

`npm install --save git+https://github.com/mmig/libflac.js.git`

and import as:

`var Flac = require('../node_modules/libflacjs/dist/libflac4-1.3.2.js');`


Perhaps put this into the documentation for react users?

**Comment by russaa** [comment]
could you check if
```javascript
var Flac = require('libflacjs');
```
works too for use with `reactjs` (after npm-installing/your first step)?

**Comment by jay-shah** [comment]
@russaa 
```javascript
var Flac = require('libflacjs')()
```
 gets the 'can't find module error'.

**Comment by russaa** [comment]
OK, thanks for testing & providing a solution -- I'll add it to the README

**Comment by ewertoncode** [comment]
Hi!
@jay-shah I tried import like you said, but I get:

blob:http://localhost:3000/d13de7fc-b381-4ef0-b5c0-30f335e50e67:2 Uncaught ReferenceError: __webpack_require__ is not defined 

var Flac = __webpack_require__(/*! ./../../../node_modules/libflacjs/dist/libflac4-1.3.2 */ "./node_modules/libflacjs/dist/libflac4-1.3.2.js");

In my code:
`
export default () => {
    const Flac = require('./../../../node_modules/libflacjs/dist/libflac4-1.3.2');
    ...
}
`
Can you help me?

Thanks!
